version: "3.9"
services:
  mysql:
    container_name: mysql_container
    image: mysql:8.0.26
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_logs:/var/log/mysql
    networks:
      sample-network:
        ipv4_address: '192.168.240.13'
    extra_hosts:
      - 'mysql.example.com:192.168.240.13'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_HOST: mysql.example.com
      MYSQL_ROOT_PASSWORD: TF6JFl6tjQif2Q
      MYSQL_USER: sampleuser
      MYSQL_PASSWORD: 6cHrgHz8LzMbOQ
      MYSQL_DATABASE: test

volumes:
  mysql_data:
    driver: local
  mysql_logs:
    driver: local
networks:
  sample-network:
    external: true
